[package]
name = "kube-operator-util"
version = "1.2.1"
edition = "2024"
description = "Utilities for Kubernetes operators"
homepage = "https://github.com/wdonne/kube-operator-util"
repository = "https://github.com/wdonne/kube-operator-util"
license = "BSD-2-Clause"
readme = "README.md"
keywords = ["kubernetes", "operator"]
exclude = ["*.iml"]

[dependencies]
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
chrono = "0.4.45"
k8s-openapi = { version = "0.28.0", features = ["v1_36"] }
kube = { version = "4.2.0", features = ["runtime", "client"] }
kube-core = "4.2.0"
log = "0.4.33"
